version: "3.8"

services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    restart: unless-stopped
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      network:
        ipv4_address: 172.16.0.29

  app:
    build:
      dockerfile: Dockerfile.dev
    container_name: container-name
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:9000
      - 5678:5678 # For debugging
    networks:
      network:
        ipv4_address: 172.16.0.11
    
