version: "8.3"

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./scripts/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    ports:
      - ${NGINX_PORT_OUT}:80
    networks:
      network:
        ipv4_address: 172.16.0.2
  
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    volumes:
      - ./scripts/mysql/init_dev.sql:/docker-entrypoint-initdb.d/1.sql
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      network:
        ipv4_address: 172.16.0.39
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - nginx
      - mysql

volumes:
  dbdata:

networks:
  network:
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16
          gateway: 172.16.0.1