FROM php:8.2-fpm-alpine

ENV LANG=C.UTF-8

WORKDIR /var/www/html

# Install system dependencies
RUN apk update && apk add git curl zip unzip

# MySQL/Mariadb extensions
RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable mysqli
#RUN docker-php-ext-install mysqli pdo pdo_mysql mbstring exif pcntl bcmath gd && docker-php-ext-enable mysqli

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
